### ISSUE TITLE
WP login bug caused by JS Composer code

### ISSUE THREAD

**Issue by evergreenacu** [VisualComposer/builder#690]
I randomly receive the following error when logging into WP-admin:

There has been a critical error on your website. Please check your site admin email inbox for instructions.
Learn more about debugging in WordPress.

Bluehost has advised that the error is emanating from the following:
/home3/XXXXXXX/public_html/wp-content/plugins/js_composer/include/classes/updaters/class-vc-updating-manager.php on line 128 

I am reporting this error to you for correction.

**Comment by iamrohan** [comment]
Hi, The error shared, is arising from WPBakery Page Builder plugin. The Visual Composer Website Builder: http://visualcomposer.com/ and WPBakery Page Builder: https://wpbakery.com/ are two independent products.

You can find more info here: https://visualcomposer.com/docs/faq/visual-composer-website-builder-vs-wpbakery-page-builder/

As the issue is related to WPBakery Page Builder, please open a ticket via it's support portal: http://support.wpbakery.com/ and share your temporary login details in it, so that it can be checked further.

**Comment by evergreenacu** [comment]
ok thanks - I'll raise it with WPB
